// flow-typed signature: d82b7929ef4d442683104eb6e8e9b0d2
// flow-typed version: <<STUB>>/consolidated-events_v^1.1.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'consolidated-events'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'consolidated-events' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'consolidated-events/__tests__/canUsePassiveEventListeners-test' {
  declare module.exports: any;
}

declare module 'consolidated-events/__tests__/eventOptionsKey-test' {
  declare module.exports: any;
}

declare module 'consolidated-events/__tests__/index-test' {
  declare module.exports: any;
}

declare module 'consolidated-events/__tests__/normalizeEventOptions-test' {
  declare module.exports: any;
}

declare module 'consolidated-events/__tests__/TargetEventHandlers-test' {
  declare module.exports: any;
}

declare module 'consolidated-events/lib/canUseDOM' {
  declare module.exports: any;
}

declare module 'consolidated-events/lib/canUsePassiveEventListeners' {
  declare module.exports: any;
}

declare module 'consolidated-events/lib/eventOptionsKey' {
  declare module.exports: any;
}

declare module 'consolidated-events/lib/index' {
  declare module.exports: any;
}

declare module 'consolidated-events/lib/normalizeEventOptions' {
  declare module.exports: any;
}

declare module 'consolidated-events/lib/TargetEventHandlers' {
  declare module.exports: any;
}

declare module 'consolidated-events/src/canUseDOM' {
  declare module.exports: any;
}

declare module 'consolidated-events/src/canUsePassiveEventListeners' {
  declare module.exports: any;
}

declare module 'consolidated-events/src/eventOptionsKey' {
  declare module.exports: any;
}

declare module 'consolidated-events/src/index' {
  declare module.exports: any;
}

declare module 'consolidated-events/src/normalizeEventOptions' {
  declare module.exports: any;
}

declare module 'consolidated-events/src/TargetEventHandlers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'consolidated-events/__tests__/canUsePassiveEventListeners-test.js' {
  declare module.exports: $Exports<'consolidated-events/__tests__/canUsePassiveEventListeners-test'>;
}
declare module 'consolidated-events/__tests__/eventOptionsKey-test.js' {
  declare module.exports: $Exports<'consolidated-events/__tests__/eventOptionsKey-test'>;
}
declare module 'consolidated-events/__tests__/index-test.js' {
  declare module.exports: $Exports<'consolidated-events/__tests__/index-test'>;
}
declare module 'consolidated-events/__tests__/normalizeEventOptions-test.js' {
  declare module.exports: $Exports<'consolidated-events/__tests__/normalizeEventOptions-test'>;
}
declare module 'consolidated-events/__tests__/TargetEventHandlers-test.js' {
  declare module.exports: $Exports<'consolidated-events/__tests__/TargetEventHandlers-test'>;
}
declare module 'consolidated-events/lib/canUseDOM.js' {
  declare module.exports: $Exports<'consolidated-events/lib/canUseDOM'>;
}
declare module 'consolidated-events/lib/canUsePassiveEventListeners.js' {
  declare module.exports: $Exports<'consolidated-events/lib/canUsePassiveEventListeners'>;
}
declare module 'consolidated-events/lib/eventOptionsKey.js' {
  declare module.exports: $Exports<'consolidated-events/lib/eventOptionsKey'>;
}
declare module 'consolidated-events/lib/index.js' {
  declare module.exports: $Exports<'consolidated-events/lib/index'>;
}
declare module 'consolidated-events/lib/normalizeEventOptions.js' {
  declare module.exports: $Exports<'consolidated-events/lib/normalizeEventOptions'>;
}
declare module 'consolidated-events/lib/TargetEventHandlers.js' {
  declare module.exports: $Exports<'consolidated-events/lib/TargetEventHandlers'>;
}
declare module 'consolidated-events/src/canUseDOM.js' {
  declare module.exports: $Exports<'consolidated-events/src/canUseDOM'>;
}
declare module 'consolidated-events/src/canUsePassiveEventListeners.js' {
  declare module.exports: $Exports<'consolidated-events/src/canUsePassiveEventListeners'>;
}
declare module 'consolidated-events/src/eventOptionsKey.js' {
  declare module.exports: $Exports<'consolidated-events/src/eventOptionsKey'>;
}
declare module 'consolidated-events/src/index.js' {
  declare module.exports: $Exports<'consolidated-events/src/index'>;
}
declare module 'consolidated-events/src/normalizeEventOptions.js' {
  declare module.exports: $Exports<'consolidated-events/src/normalizeEventOptions'>;
}
declare module 'consolidated-events/src/TargetEventHandlers.js' {
  declare module.exports: $Exports<'consolidated-events/src/TargetEventHandlers'>;
}
