// flow-typed signature: 745a7d70a995e8900b87095b7f7d9121
// flow-typed version: <<STUB>>/mark.js_v^8.11.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mark.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mark.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mark.js/build/templates/jquery.mark' {
  declare module.exports: any;
}

declare module 'mark.js/build/templates/mark' {
  declare module.exports: any;
}

declare module 'mark.js/dist/jquery.mark.es6' {
  declare module.exports: any;
}

declare module 'mark.js/dist/jquery.mark.es6.min' {
  declare module.exports: any;
}

declare module 'mark.js/dist/jquery.mark' {
  declare module.exports: any;
}

declare module 'mark.js/dist/jquery.mark.min' {
  declare module.exports: any;
}

declare module 'mark.js/dist/mark.es6' {
  declare module.exports: any;
}

declare module 'mark.js/dist/mark.es6.min' {
  declare module.exports: any;
}

declare module 'mark.js/dist/mark' {
  declare module.exports: any;
}

declare module 'mark.js/dist/mark.min' {
  declare module.exports: any;
}

declare module 'mark.js/Gruntfile' {
  declare module.exports: any;
}

declare module 'mark.js/karma.conf-ci' {
  declare module.exports: any;
}

declare module 'mark.js/karma.conf' {
  declare module.exports: any;
}

declare module 'mark.js/src/mark' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/basic/accuracy-exactly' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/basic/done' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/basic/each' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/basic/empty' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/basic/filter' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/basic/ignore-joiners' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/basic/main' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/basic/merge-blanks' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/iframes/across' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/iframes/main' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/iframes/nested' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/nested/main' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/regexp/filter' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/regexp/ignore-groups' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/regexp/infinite' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/across-elements/regexp/main' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/accuracy-complementary-limiters' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/accuracy-complementary' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/accuracy-exactly-limiters' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/accuracy-exactly' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/accuracy-partially' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/array-keyword' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/case-sensitive-diacritics' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/case-sensitive-synonyms-diacritics' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/case-sensitive-synonyms' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/case-sensitive' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/context-array' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/context-direct' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/context-nodelist' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/context-string' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/custom-element-class-unmark' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/custom-element-class' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/debug' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/diacritics-vietnamese' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/diacritics' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/done' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/duplicate-context' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/duplicate-keyword' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/each' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/empty' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/entities' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/escape' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/events' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/exclude' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/filter' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/ignore-joiners-diacritics' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/ignore-joiners-escape' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/ignore-joiners-synonyms-diacritics' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/ignore-joiners-synonyms' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/ignore-joiners' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/ignore-punctuation-accuracy' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/ignore-punctuation-ignore-joiners' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/ignore-punctuation-separate-word-search' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/ignore-punctuation-synonyms-diacritics' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/ignore-punctuation-synonyms' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/ignore-punctuation' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/jquery' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/large-document' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/main' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/manipulated-mark' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/merge-blanks' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/nested-mark' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/no-match' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/no-options' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/same-keywords' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/script-style' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/separate-word-search-blank' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/separate-word-search' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/synonyms-diacritics' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/synonyms-merge-blanks' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/synonyms-no-match' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/synonyms-not-empty' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/synonyms' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/unmark-exclude' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/unmark-jquery' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/unmark' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/wildcards-between-words' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/wildcards-diacritics' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/wildcards-escaped' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/wildcards-ignore-joiners-synonyms' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/wildcards-synonyms' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/basic/wildcards' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/configuration' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/iframes/disabled' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/iframes/exclude' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/iframes/inaccessible' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/iframes/main' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/iframes/nested-unmark' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/iframes/nested' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/iframes/onload' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/iframes/order' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/iframes/readystate' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/iframes/unmark-same-instance' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/iframes/unmark' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/nested/main' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/nested/unmark' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/ranges/across-elements' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/ranges/each' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/ranges/filter' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/ranges/iframes' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/ranges/main' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/ranges/no-match' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/ranges/overlap' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/regexp/done' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/regexp/filter' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/regexp/ignore-groups' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/regexp/infinite' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/regexp/jquery' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/regexp/main' {
  declare module.exports: any;
}

declare module 'mark.js/test/specs/regexp/no-match' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mark.js/build/templates/jquery.mark.js' {
  declare module.exports: $Exports<'mark.js/build/templates/jquery.mark'>;
}
declare module 'mark.js/build/templates/mark.js' {
  declare module.exports: $Exports<'mark.js/build/templates/mark'>;
}
declare module 'mark.js/dist/jquery.mark.es6.js' {
  declare module.exports: $Exports<'mark.js/dist/jquery.mark.es6'>;
}
declare module 'mark.js/dist/jquery.mark.es6.min.js' {
  declare module.exports: $Exports<'mark.js/dist/jquery.mark.es6.min'>;
}
declare module 'mark.js/dist/jquery.mark.js' {
  declare module.exports: $Exports<'mark.js/dist/jquery.mark'>;
}
declare module 'mark.js/dist/jquery.mark.min.js' {
  declare module.exports: $Exports<'mark.js/dist/jquery.mark.min'>;
}
declare module 'mark.js/dist/mark.es6.js' {
  declare module.exports: $Exports<'mark.js/dist/mark.es6'>;
}
declare module 'mark.js/dist/mark.es6.min.js' {
  declare module.exports: $Exports<'mark.js/dist/mark.es6.min'>;
}
declare module 'mark.js/dist/mark.js' {
  declare module.exports: $Exports<'mark.js/dist/mark'>;
}
declare module 'mark.js/dist/mark.min.js' {
  declare module.exports: $Exports<'mark.js/dist/mark.min'>;
}
declare module 'mark.js/Gruntfile.js' {
  declare module.exports: $Exports<'mark.js/Gruntfile'>;
}
declare module 'mark.js/karma.conf-ci.js' {
  declare module.exports: $Exports<'mark.js/karma.conf-ci'>;
}
declare module 'mark.js/karma.conf.js' {
  declare module.exports: $Exports<'mark.js/karma.conf'>;
}
declare module 'mark.js/src/mark.js' {
  declare module.exports: $Exports<'mark.js/src/mark'>;
}
declare module 'mark.js/test/specs/across-elements/basic/accuracy-exactly.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/basic/accuracy-exactly'>;
}
declare module 'mark.js/test/specs/across-elements/basic/done.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/basic/done'>;
}
declare module 'mark.js/test/specs/across-elements/basic/each.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/basic/each'>;
}
declare module 'mark.js/test/specs/across-elements/basic/empty.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/basic/empty'>;
}
declare module 'mark.js/test/specs/across-elements/basic/filter.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/basic/filter'>;
}
declare module 'mark.js/test/specs/across-elements/basic/ignore-joiners.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/basic/ignore-joiners'>;
}
declare module 'mark.js/test/specs/across-elements/basic/main.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/basic/main'>;
}
declare module 'mark.js/test/specs/across-elements/basic/merge-blanks.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/basic/merge-blanks'>;
}
declare module 'mark.js/test/specs/across-elements/iframes/across.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/iframes/across'>;
}
declare module 'mark.js/test/specs/across-elements/iframes/main.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/iframes/main'>;
}
declare module 'mark.js/test/specs/across-elements/iframes/nested.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/iframes/nested'>;
}
declare module 'mark.js/test/specs/across-elements/nested/main.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/nested/main'>;
}
declare module 'mark.js/test/specs/across-elements/regexp/filter.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/regexp/filter'>;
}
declare module 'mark.js/test/specs/across-elements/regexp/ignore-groups.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/regexp/ignore-groups'>;
}
declare module 'mark.js/test/specs/across-elements/regexp/infinite.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/regexp/infinite'>;
}
declare module 'mark.js/test/specs/across-elements/regexp/main.js' {
  declare module.exports: $Exports<'mark.js/test/specs/across-elements/regexp/main'>;
}
declare module 'mark.js/test/specs/basic/accuracy-complementary-limiters.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/accuracy-complementary-limiters'>;
}
declare module 'mark.js/test/specs/basic/accuracy-complementary.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/accuracy-complementary'>;
}
declare module 'mark.js/test/specs/basic/accuracy-exactly-limiters.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/accuracy-exactly-limiters'>;
}
declare module 'mark.js/test/specs/basic/accuracy-exactly.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/accuracy-exactly'>;
}
declare module 'mark.js/test/specs/basic/accuracy-partially.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/accuracy-partially'>;
}
declare module 'mark.js/test/specs/basic/array-keyword.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/array-keyword'>;
}
declare module 'mark.js/test/specs/basic/case-sensitive-diacritics.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/case-sensitive-diacritics'>;
}
declare module 'mark.js/test/specs/basic/case-sensitive-synonyms-diacritics.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/case-sensitive-synonyms-diacritics'>;
}
declare module 'mark.js/test/specs/basic/case-sensitive-synonyms.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/case-sensitive-synonyms'>;
}
declare module 'mark.js/test/specs/basic/case-sensitive.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/case-sensitive'>;
}
declare module 'mark.js/test/specs/basic/context-array.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/context-array'>;
}
declare module 'mark.js/test/specs/basic/context-direct.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/context-direct'>;
}
declare module 'mark.js/test/specs/basic/context-nodelist.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/context-nodelist'>;
}
declare module 'mark.js/test/specs/basic/context-string.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/context-string'>;
}
declare module 'mark.js/test/specs/basic/custom-element-class-unmark.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/custom-element-class-unmark'>;
}
declare module 'mark.js/test/specs/basic/custom-element-class.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/custom-element-class'>;
}
declare module 'mark.js/test/specs/basic/debug.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/debug'>;
}
declare module 'mark.js/test/specs/basic/diacritics-vietnamese.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/diacritics-vietnamese'>;
}
declare module 'mark.js/test/specs/basic/diacritics.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/diacritics'>;
}
declare module 'mark.js/test/specs/basic/done.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/done'>;
}
declare module 'mark.js/test/specs/basic/duplicate-context.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/duplicate-context'>;
}
declare module 'mark.js/test/specs/basic/duplicate-keyword.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/duplicate-keyword'>;
}
declare module 'mark.js/test/specs/basic/each.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/each'>;
}
declare module 'mark.js/test/specs/basic/empty.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/empty'>;
}
declare module 'mark.js/test/specs/basic/entities.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/entities'>;
}
declare module 'mark.js/test/specs/basic/escape.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/escape'>;
}
declare module 'mark.js/test/specs/basic/events.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/events'>;
}
declare module 'mark.js/test/specs/basic/exclude.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/exclude'>;
}
declare module 'mark.js/test/specs/basic/filter.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/filter'>;
}
declare module 'mark.js/test/specs/basic/ignore-joiners-diacritics.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/ignore-joiners-diacritics'>;
}
declare module 'mark.js/test/specs/basic/ignore-joiners-escape.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/ignore-joiners-escape'>;
}
declare module 'mark.js/test/specs/basic/ignore-joiners-synonyms-diacritics.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/ignore-joiners-synonyms-diacritics'>;
}
declare module 'mark.js/test/specs/basic/ignore-joiners-synonyms.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/ignore-joiners-synonyms'>;
}
declare module 'mark.js/test/specs/basic/ignore-joiners.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/ignore-joiners'>;
}
declare module 'mark.js/test/specs/basic/ignore-punctuation-accuracy.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/ignore-punctuation-accuracy'>;
}
declare module 'mark.js/test/specs/basic/ignore-punctuation-ignore-joiners.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/ignore-punctuation-ignore-joiners'>;
}
declare module 'mark.js/test/specs/basic/ignore-punctuation-separate-word-search.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/ignore-punctuation-separate-word-search'>;
}
declare module 'mark.js/test/specs/basic/ignore-punctuation-synonyms-diacritics.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/ignore-punctuation-synonyms-diacritics'>;
}
declare module 'mark.js/test/specs/basic/ignore-punctuation-synonyms.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/ignore-punctuation-synonyms'>;
}
declare module 'mark.js/test/specs/basic/ignore-punctuation.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/ignore-punctuation'>;
}
declare module 'mark.js/test/specs/basic/jquery.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/jquery'>;
}
declare module 'mark.js/test/specs/basic/large-document.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/large-document'>;
}
declare module 'mark.js/test/specs/basic/main.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/main'>;
}
declare module 'mark.js/test/specs/basic/manipulated-mark.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/manipulated-mark'>;
}
declare module 'mark.js/test/specs/basic/merge-blanks.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/merge-blanks'>;
}
declare module 'mark.js/test/specs/basic/nested-mark.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/nested-mark'>;
}
declare module 'mark.js/test/specs/basic/no-match.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/no-match'>;
}
declare module 'mark.js/test/specs/basic/no-options.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/no-options'>;
}
declare module 'mark.js/test/specs/basic/same-keywords.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/same-keywords'>;
}
declare module 'mark.js/test/specs/basic/script-style.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/script-style'>;
}
declare module 'mark.js/test/specs/basic/separate-word-search-blank.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/separate-word-search-blank'>;
}
declare module 'mark.js/test/specs/basic/separate-word-search.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/separate-word-search'>;
}
declare module 'mark.js/test/specs/basic/synonyms-diacritics.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/synonyms-diacritics'>;
}
declare module 'mark.js/test/specs/basic/synonyms-merge-blanks.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/synonyms-merge-blanks'>;
}
declare module 'mark.js/test/specs/basic/synonyms-no-match.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/synonyms-no-match'>;
}
declare module 'mark.js/test/specs/basic/synonyms-not-empty.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/synonyms-not-empty'>;
}
declare module 'mark.js/test/specs/basic/synonyms.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/synonyms'>;
}
declare module 'mark.js/test/specs/basic/unmark-exclude.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/unmark-exclude'>;
}
declare module 'mark.js/test/specs/basic/unmark-jquery.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/unmark-jquery'>;
}
declare module 'mark.js/test/specs/basic/unmark.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/unmark'>;
}
declare module 'mark.js/test/specs/basic/wildcards-between-words.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/wildcards-between-words'>;
}
declare module 'mark.js/test/specs/basic/wildcards-diacritics.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/wildcards-diacritics'>;
}
declare module 'mark.js/test/specs/basic/wildcards-escaped.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/wildcards-escaped'>;
}
declare module 'mark.js/test/specs/basic/wildcards-ignore-joiners-synonyms.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/wildcards-ignore-joiners-synonyms'>;
}
declare module 'mark.js/test/specs/basic/wildcards-synonyms.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/wildcards-synonyms'>;
}
declare module 'mark.js/test/specs/basic/wildcards.js' {
  declare module.exports: $Exports<'mark.js/test/specs/basic/wildcards'>;
}
declare module 'mark.js/test/specs/configuration.js' {
  declare module.exports: $Exports<'mark.js/test/specs/configuration'>;
}
declare module 'mark.js/test/specs/iframes/disabled.js' {
  declare module.exports: $Exports<'mark.js/test/specs/iframes/disabled'>;
}
declare module 'mark.js/test/specs/iframes/exclude.js' {
  declare module.exports: $Exports<'mark.js/test/specs/iframes/exclude'>;
}
declare module 'mark.js/test/specs/iframes/inaccessible.js' {
  declare module.exports: $Exports<'mark.js/test/specs/iframes/inaccessible'>;
}
declare module 'mark.js/test/specs/iframes/main.js' {
  declare module.exports: $Exports<'mark.js/test/specs/iframes/main'>;
}
declare module 'mark.js/test/specs/iframes/nested-unmark.js' {
  declare module.exports: $Exports<'mark.js/test/specs/iframes/nested-unmark'>;
}
declare module 'mark.js/test/specs/iframes/nested.js' {
  declare module.exports: $Exports<'mark.js/test/specs/iframes/nested'>;
}
declare module 'mark.js/test/specs/iframes/onload.js' {
  declare module.exports: $Exports<'mark.js/test/specs/iframes/onload'>;
}
declare module 'mark.js/test/specs/iframes/order.js' {
  declare module.exports: $Exports<'mark.js/test/specs/iframes/order'>;
}
declare module 'mark.js/test/specs/iframes/readystate.js' {
  declare module.exports: $Exports<'mark.js/test/specs/iframes/readystate'>;
}
declare module 'mark.js/test/specs/iframes/unmark-same-instance.js' {
  declare module.exports: $Exports<'mark.js/test/specs/iframes/unmark-same-instance'>;
}
declare module 'mark.js/test/specs/iframes/unmark.js' {
  declare module.exports: $Exports<'mark.js/test/specs/iframes/unmark'>;
}
declare module 'mark.js/test/specs/nested/main.js' {
  declare module.exports: $Exports<'mark.js/test/specs/nested/main'>;
}
declare module 'mark.js/test/specs/nested/unmark.js' {
  declare module.exports: $Exports<'mark.js/test/specs/nested/unmark'>;
}
declare module 'mark.js/test/specs/ranges/across-elements.js' {
  declare module.exports: $Exports<'mark.js/test/specs/ranges/across-elements'>;
}
declare module 'mark.js/test/specs/ranges/each.js' {
  declare module.exports: $Exports<'mark.js/test/specs/ranges/each'>;
}
declare module 'mark.js/test/specs/ranges/filter.js' {
  declare module.exports: $Exports<'mark.js/test/specs/ranges/filter'>;
}
declare module 'mark.js/test/specs/ranges/iframes.js' {
  declare module.exports: $Exports<'mark.js/test/specs/ranges/iframes'>;
}
declare module 'mark.js/test/specs/ranges/main.js' {
  declare module.exports: $Exports<'mark.js/test/specs/ranges/main'>;
}
declare module 'mark.js/test/specs/ranges/no-match.js' {
  declare module.exports: $Exports<'mark.js/test/specs/ranges/no-match'>;
}
declare module 'mark.js/test/specs/ranges/overlap.js' {
  declare module.exports: $Exports<'mark.js/test/specs/ranges/overlap'>;
}
declare module 'mark.js/test/specs/regexp/done.js' {
  declare module.exports: $Exports<'mark.js/test/specs/regexp/done'>;
}
declare module 'mark.js/test/specs/regexp/filter.js' {
  declare module.exports: $Exports<'mark.js/test/specs/regexp/filter'>;
}
declare module 'mark.js/test/specs/regexp/ignore-groups.js' {
  declare module.exports: $Exports<'mark.js/test/specs/regexp/ignore-groups'>;
}
declare module 'mark.js/test/specs/regexp/infinite.js' {
  declare module.exports: $Exports<'mark.js/test/specs/regexp/infinite'>;
}
declare module 'mark.js/test/specs/regexp/jquery.js' {
  declare module.exports: $Exports<'mark.js/test/specs/regexp/jquery'>;
}
declare module 'mark.js/test/specs/regexp/main.js' {
  declare module.exports: $Exports<'mark.js/test/specs/regexp/main'>;
}
declare module 'mark.js/test/specs/regexp/no-match.js' {
  declare module.exports: $Exports<'mark.js/test/specs/regexp/no-match'>;
}
